language: node_js
node_js:
- '12'
- '11'
- '10'
- '8'
cache: npm
install: npm install
before_install:
  - if [[ `npm -v` = 3* ]]; then npm i -g npm@5; fi
sudo: 'false'
before_script:
  - npm ls
  - npm run build
